version: '3'
services:
  reddit-collector:
    build: RedditCollector/
    volumes:
      - ./RedditCollector/:/RedditCollector
      - ./RedditCollector/requirements.txt:/RedditCollector/requirements.txt
    command: ["python", "app.py"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27027:27017
    logging:
      driver: "none"

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5555:5432

  meta:
    image: metabase/metabase
    ports:
      - 12345:3000
    depends_on:
      - postgresdb

  airflow:
    build: airflow/
    volumes:
      - ./airflow/dags/:/airflow/dags/
      - ./airflow/requirements.txt:/airflow/requirements.txt
    ports:
      - "8081:8080"
    command: ["webserver", "scheduler"]
    depends_on:
      - mongodb
      - postgresdb